//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dts
{
    using System;
    using System.Collections.Generic;
    
    public partial class cancha
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cancha()
        {
            this.partidoes = new HashSet<partido>();
        }
    
        public int idcancha { get; set; }
        public string cannombre { get; set; }
        public string canarea { get; set; }
        public string candireccion { get; set; }
        public string candisponibilidad { get; set; }
        public string canreputacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partido> partidoes { get; set; }
    }
}
