//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dts
{
    using System;
    using System.Collections.Generic;
    
    public partial class partido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public partido()
        {
            this.jugadors = new HashSet<jugador>();
        }
    
        public int parid { get; set; }
        public string partitulo { get; set; }
        public System.DateTime parhora { get; set; }
        public int cancha_idcancha { get; set; }
    
        public virtual cancha cancha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jugador> jugadors { get; set; }
    }
}
